### ISSUE TITLE
undefined reference '__modsi3' and '__mulsi3'

### ISSUE THREAD

**Issue by agentbooth** [mikehaertel/unixpc-gcc#1]
This project is great, thanks for putting it together!

In attempting to cross-compile some code, I got the following:
/tmp/ccgND8Xu.o(.text+0x68c):fake: undefined reference to '__mulsi3'
/tmp/ccgND8Xu.o(.text+0x7fa):fake: undefined reference to '__modsi3'

Apparently from libgcc
Runtime Function: int __modsi3 (int a, int b) - return the remainder of the signed division of a and b.
Runtime Function: int __mulsi3 (int a, int b) -  return the product of a and b.

Any idea what the issue here might be?

**Comment by mikehaertel** [comment]
Yeah.  Normally when you compile GCC natively, it builds those functions by compiling with the native compiler.  When you're building a cross-gcc, it doesn't have the native compiler so it can't do that, and you have to provide your own.  I'm working on adding 6 of those functions right now for integer arithmetic.  There will also be a similar problem with runtime support for floating-point arithmetic; the delivery time for that will be a little bit longer.

**Comment by agentbooth** [comment]
Ok great, thanks for the explanation.

**Comment by mikehaertel** [comment]
I've added these functions to the build.  Now the only required runtime that I'm aware of that remains unimplemented is floating point arithmetic.
