### ISSUE TITLE
GCC floating point runtime support is unimplemented

### ISSUE THREAD

**Issue by mikehaertel** [mikehaertel/unixpc-gcc#2]
On soft-float machines, GCC requires various runtime library functions to support floating point arithmetic.  These are not yet included.

**Comment by AlainKnaff** [comment]
Hi,

Attached patch add floating point support, by calling UnixPC's double library functions (dbadd__, dbsub__, dbmul__).

[float.txt](https://github.com/mikehaertel/unixpc-gcc/files/9649660/float.txt)

A couple of remarks:
- Single-with float operations are handled by casting to double, doing the operation, and casting the result back to float. UnixPC's native cc seems to do it the same way.
- NaN's are not handled (UnixPC's library seems to return 0 for operations such as sqrt(-1.0) that should yield NaN). This simplifies comparison operators (<, >, <=, ...), as they now simply all map to subtraction. Actual comparison is done on the high double word (integer) of the double value returned by the subtraction.
- __negdf2 seems not to be needed. GCC does that inline, which makes sense at is just the inversion of the sign bit (high bit).

Regards,

Alain

**Comment by mikehaertel** [comment]
Alain, thanks!  This is an impressive contribution.
BTW my email address is mike@ducky.net
