### ISSUE TITLE
UnixPC cross compiler: remarks & improvements

### ISSUE THREAD

**Issue by AlainKnaff** [mikehaertel/unixpc-gcc#3]
(No really an issue, but unfortunately I couldn't find any E-Mail address where to contact you directly)

Hi,

Following a post to comp.sys.3b1 by Aharon Robbins, I found your UnixPC cross compiler at https://github.com/mikehaertel/unixpc-gcc

While setting it up, I came across 2 documentation issues:

1. On a 64 bit build machine, installing the libc6-dev-i386 Debian package is not enough, you also need linux-libc-dev:i386, or else asm/errno.h cannot be found.

2. In general, texinfo should not be installed. Apparently the texinfo documentation of binutils uses syntax which can no longer be processed by current versions of makeinfo, which makes the build process fail. If on the other hand there is no system texinfo, binutils will use its own, and succeed.

And I've also got suggestions for 2 improvements:

1. You don't actually need to supply your own implementation of divsi3 modsi3 mulsi3 udivsi3 umodsi3, it's enough to tell the compiler the correct names, see the attached muldiv.txt patch
[muldiv.txt](https://github.com/mikehaertel/unixpc-gcc/files/9619848/muldiv.txt)

2. Actually, gcc can be compiled on 64 bit just fine. Indeed, the error happens in a sanity check which is overly strict, just yanking out that check fixes the issue. See the attached 64bit.txt patch
[64bit.txt](https://github.com/mikehaertel/unixpc-gcc/files/9619847/64bit.txt)

And I'm glad to say that your cross compiler can compile much more than just a simple hello world program. I tried compiling my mtools package: compilation works great, both before and after my suggested improvements.

Regards,

Alain

**Comment by mikehaertel** [comment]
Alain,

Thanks!  I've incorporated the fix suggested in 64bit.txt, and also added a texinfo workaround to the build script.  (You were the second person to complain about that!)

I'm going to keep my own versions of the GCC runtime support routines in the build, because a side goal for me of doing this project is to develop a complete GCC m68k runtime.

Best regards,

Mike
